server:
  servlet:
    context-path: /zetton
spring:
  profiles:
    active: dev
  resources:
    add-mappings: false
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    cache: false
    encoding: utf-8
###################  mybatis-plus配置  ###################
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  # mapper-locations: classpath*:/mapper/init/*.xml
  typeAliasesPackage: >
    com.zetton.thymeleaf.entity
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    jdbc-type-for-null: 'null' #配置JdbcTypeForNull, oracle数据库必须配置

logging:
  level:
    org.springframework.web.servlet: ERROR
