###################  自定义配置  ###################
common:
  csvApp: F:\app.csv
  csvLog: F:\log.csv

server:
  servlet:
    context-path: /zetton
spring:
  profiles:
    active: dev
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      time-to-live: 600000ms
      use-key-prefix: on
    cache-names: userCache,allUsersCache
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
  resources:
    add-mappings: false
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    cache: false
    encoding: utf-8
  batch:
    job:
      #启动时要执行的job，默认执行全部job
      names: job1,job2
      #是否自动执行定义的job，默认是
      enabled: true
      #是否初始化Spring Batch的数据库，默认为是
    initialize-schema: always
    #设置Spring Batch的数据库表的前缀
    table-prefix: batch_
    #设置默认初始化batch的sql文件路径
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
###################  mybatis-plus配置  ###################
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  # mapper-locations: classpath*:/mapper/init/*.xml
  typeAliasesPackage: >
    com.zetton.thymeleaf.entity
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    jdbc-type-for-null: 'null' #配置JdbcTypeForNull, oracle数据库必须配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.web.servlet: ERROR
cxf:
  path: /services
