
package com.zetton.thymeleaf.webserviceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonServiceImplService", targetNamespace = "http://entity.thymeleaf.zetton.com/", wsdlLocation = "http://localhost:8082/zetton/services/CommonService?wsdl")
public class CommonServiceImplServiceLocal
    extends Service
{

    private final static URL COMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COMMONSERVICEIMPLSERVICE_QNAME = new QName("http://entity.thymeleaf.zetton.com/", "CommonServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/zetton/services/CommonService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COMMONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CommonServiceImplServiceLocal() {
        super(__getWsdlLocation(), COMMONSERVICEIMPLSERVICE_QNAME);
    }

    public CommonServiceImplServiceLocal(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommonServiceImplServiceLocal(URL wsdlLocation) {
        super(wsdlLocation, COMMONSERVICEIMPLSERVICE_QNAME);
    }

    public CommonServiceImplServiceLocal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommonServiceImplServiceLocal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonServiceImplServiceLocal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonService
     */
    @WebEndpoint(name = "CommonServicePort")
    public CommonService getCommonServicePort() {
        return super.getPort(new QName("http://entity.thymeleaf.zetton.com/", "CommonServicePort"), CommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonService
     */
    @WebEndpoint(name = "CommonServicePort")
    public CommonService getCommonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://entity.thymeleaf.zetton.com/", "CommonServicePort"), CommonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COMMONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
